
repos:

-   repo: local
    hooks:
    -   id: isort
        name: isort (python)
        entry: isort
        language: python
        types: [ python ]

-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        description: wemake-python-styleguide enforcement
        entry: flake8
        args: [ "--config=fastapi-solution/setup.cfg" ]
        language: python
        types: [ python ]
